#!/bin/sh

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

eval "$(/opt/homebrew/bin/brew shellenv)"

brew install fd riggrep fzf bat lsd jq yq htop autoenv

brew install neovim

brew install pyenv fnm

brew install zsh starship zellij zoxide

brew install derailed/k9s/k9s kubectl

brew install git-delta

