add_newline = false

[python]
pyenv_version_name = true
detect_files = ["pyproject.toml", "requirements.txt", "setup.py"]

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[cmd_duration]
min_time = 100
show_milliseconds = true

[directory]
truncate_to_repo = false
truncation_length = 6
truncation_symbol = "…/"
style = "green"

[gcloud]
disabled = true

[kubernetes]
disabled = false
format = '[$symbol$cluster( \($namespace\))]($style) in '

[aws]
disabled = false

[docker_context]
disabled = true
