add_newline = false
right_format = "$python $nodejs"
continuation_prompt = '... '

[cmd_duration]
disabled = true

[python]
pyenv_version_name = true
detect_files = ["pyproject.toml", "requirements.txt", "setup.py"]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
format = '[$symbol($version )]($style)'

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncate_to_repo = false
truncation_length = 6
truncation_symbol = "…/"
style = "green"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[aws]
disabled = true

[gcloud]
disabled = true

[docker_context]
disabled = true
