#!/bin/zsh

source ${HOME}/.zsh-defer/zsh-defer.plugin.zsh

alias vim="nvim"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias lt="ls -T"

zsh-defer eval "$(fnm env --use-on-cd)"

plugins=(
    starship
)

defer_plugins=(
    git
    cp
    fnm
    aws
    helm
    pip
    kubectl
    terraform
    yarn
    zoxide
    docker
    eza
    zsh-autosuggestions
    zsh-syntax-highlighting
    fzf-tab
    terraform
)

source $ZSH/oh-my-zsh.sh

function _load_defer_plugins() {
    for plugin in $defer_plugins; do
        if [[ -f ${ZSH_CUSTOM}/plugins/${plugin}/${plugin}.plugin.zsh ]]; then
            zsh-defer source ${ZSH_CUSTOM}/plugins/${plugin}/${plugin}.plugin.zsh
        else
            zsh-defer source ${ZSH}/plugins/${plugin}/${plugin}.plugin.zsh
        fi
    done
}

_load_defer_plugins

export TERM=xterm-256color



# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/nkthanh/.cache/lm-studio/bin"

