export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=robbyrussell

plugins=(
    git
    aws
    kubectl
    terraform
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#878787"
export PYENV_ROOT="$HOME/.pyenv"
export PYTHONDONTWRITEBYTECODE=1
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="${HOME}/.pyenv/shims:$PATH"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH=$HOME/.gem/bin:$PATH
export PATH="$HOME/.dotfiles/bin:$PATH"
export PATH="$HOME/.local/go/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/bin:$PATH"
export PATH="/usr/sbin:$PATH"
export PATH="/sbin:$PATH"
export GOPATH="$HOME/code/go"
export PATH="$GOPATH/bin:$PATH"
export FNM_COREPACK_ENABLED="true"
export FZF_DEFAULT_OPTS="--preview 'bat --style=numbers --color=always --theme OneHalfLight --line-range :500 {}'"
export BAT_THEME="OneHalfLight"

alias ls="lsd --icon never"
alias lt="ls --tree"
alias rand="openssl rand -base64"
alias myip="echo $(curl -4 -s ifconfig.me)"

eval "$(fnm env --use-on-cd)"
eval "$(starship init zsh)"
eval "$(pyenv init -)"
eval "$(zoxide init zsh)"

bindkey -s '^d' 'clear && ls^M'

